### ISSUE TITLE
`xattr` fails on non-unicode attribute names

### ISSUE THREAD

**Issue by panhania** [xattr/xattr#82] opened 2018-10-24 11:56 UTC
On Linux, flag names can be arbitrary strings of bytes:

    $ touch /tmp/foo
    $ setfattr /tmp/foo -n $'user.b\xffa\xffr' -v $'b\xffa\xffz'
    $ getfattr /tmp/foo -n $'user.b\xffa\xffr'
    (...)
    user.b�a�r="baz"

However, an attempt to list the extended attributes for that file with `xattr` fails:

    >>> from xattr import xattr
    >>> xattr('/tmp/foo').list()
    (...)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 6: invalid start byte

**Comment by mrhania** [comment] 2018-10-24 13:05
I now see that this is kind of working as expected since there is a `pyxattr_compat` module that returns attribute names undecoded.

I feel like the compatibility module should only be used for dealing with API compatibility issues and `xattr` should expose some method to retrieve unecoded attribute names as well.

**Comment by etrepum** [comment] 2018-10-24 15:35
The library was designed for OS X where utf8 is a requirement, hence the lack of easy paths to get at the raw bytes. I’d be happy to look at a PR that changes things around in a way that makes more sense to you (even if it’s just documentation).

**Comment by jmberg** [comment] 2020-01-13 08:24
Note that pyxattr_compat also has issues with bytes being passed - list may work, but at least other things certainly won't. See https://github.com/xattr/xattr/pull/88.

**Comment by griswolf** [comment] 2020-07-04 19:30
Related failure on MacOS (Catalina) for /usr/local/bin/xattr installed via pip install xattr:

> 600% xattr ~/Documents/CampSherman/excede_usage_2018-05_06.csv 
Traceback (most recent call last):
  File "/usr/local/bin/xattr", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/xattr/tool.py", line 196, in main
    attr_value = attr_value.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 5: invalid continuation byte

**Comment by TheMatt2** [comment] 2020-08-08 16:35
Can this be fixed by not printing the non-unicode characters?

I think that may be a more helpful behavior than a traceback.

**Closed** 2023-11-20 05:59 UTC
